In [1]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
#past analysis work on different dataset
# this_df = pd.read_csv('data_c30s.csv')
# this_df.head(2)

# df = this_df.drop(['brand','description','key_features','key_specifications','review_content','review_date',
#'review_title','review_username','standout_features'], axis = 1)

# df.head()

# df.index.name = 'cars_id'
# df.head()

# ratings = pd.DataFrame(df.groupby('name')['rating'].mean())
# ratings.head()

# ratings['number_of_ratings'] = df.groupby('name')['rating'].count()
# ratings.head()

# #creating the user-item interaction matrix
# cars_rating_matrix = df.pivot_table(index='cars_id', columns='name', values='rating')
# cars_rating_matrix.head()

# ratings.sort_values('number_of_ratings', ascending=False).head(10)

# #Fetching ratings for Audi A8
# desired_car_user_rating=cars_rating_matrix['Audi A8']
# desired_car_user_rating

# c

In [3]:
this_df = pd.read_csv('new_cars.csv')
this_df.head()

Users  Maruti XL6  Maruti Celerio X  Maruti Swift Dzire Tour  \
0  User1         2.5               4.5                      3.5   
1  User2         5.0               4.5                      4.0   
2  User3         4.5               4.5                      5.0   
3  User4         4.5               5.0                      3.5   
4  User5         4.5               5.0                      3.5   

   Bajaj Qute (RE60)  Ford Aspire  Lamborghini Huracan EVO  Nissan Kicks  \
0                5.0          5.0                      4.5           4.5   
1                5.0          4.5                      4.5           4.5   
2                4.5          4.5                      3.5           2.5   
3                2.0          5.0                      5.0           5.0   
4                5.0          4.0                      5.0           3.5   

   Ford Freestyle  Lamborghini Urus  ...  Toyota Yaris  MG Hector Plus  \
0             4.0               4.5  ...           4.0             5.0   
1             4.5               4.0  ...           1.0             4.5   
2             4.0               5.0  ...           5.0             4.5   
3             5.0               4.5  ...           4.5             1.0   
4             5.0               4.0  ...           4.5             2.5   

   Toyota Camry  Volkswagen Vento  Kia Sonet  MG ZS EV  Toyota Innova Crysta  \
0           5.0               4.5        5.0       4.5                   4.5   
1           4.0               3.5        5.0       3.5                   3.5   
2           5.0               5.0        5.0       2.5                   4.5   
3           5.0               4.5        5.0       2.5                   5.0   
4           5.0               4.0        4.5       4.5                   4.5   

   New Skoda Superb  MG Gloster  MG Hector  
0               4.5         4.5        4.5  
1               5.0         5.0        4.5  
2               4.5         5.0        5.0  
3               5.0         5.0        5.0  
4               5.0         5.0        3.5  

[5 rows x 126 columns]

In [4]:
df1 = pd.DataFrame(this_df.melt(id_vars = ["Users"]))
df1.columns = ['Users', 'Cars name', 'Ratings']
df1.head()

Users   Cars name  Ratings
0  User1  Maruti XL6      2.5
1  User2  Maruti XL6      5.0
2  User3  Maruti XL6      4.5
3  User4  Maruti XL6      4.5
4  User5  Maruti XL6      4.5

In [5]:
df1.shape

(3750, 3)

In [6]:
df_cars = df1.pivot(
    index = 'Cars name',
    columns = 'Users',
    values = 'Ratings'
).fillna(0)

In [7]:
df_cars.head()

Users             User1  User10  User11  User12  User13  User14  User15  \
Cars name                                                                 
Aston Martin DBX    5.0     0.0     0.0     0.0     0.0     0.0     0.0   
Audi A4             4.5     0.0     0.0     0.0     0.0     0.0     0.0   
Audi A8             4.0     0.0     0.0     0.0     0.0     0.0     0.0   
Audi Q2             5.0     0.0     0.0     0.0     0.0     0.0     0.0   
Audi Q8             5.0     0.0     0.0     0.0     0.0     0.0     0.0   

Users             User16  User17  User18  ...  User28  User29  User3  User30  \
Cars name                                 ...                                  
Aston Martin DBX     0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi A4              0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi A8              0.0     0.0     0.0  ...     0.0     0.0    5.0     0.0   
Audi Q2              0.0     0.0     0.0  ...     0.0     0.0    5.0     0.0   
Audi Q8              0.0     0.0     0.0  ...     0.0     0.0    4.5     0.0   

Users             User4  User5  User6  User7  User8  User9  
Cars name                                                   
Aston Martin DBX    0.0    0.0    0.0    0.0    0.0    0.0  
Audi A4             0.0    0.0    0.0    0.0    0.0    0.0  
Audi A8             5.0    5.0    5.0    4.5    5.0    0.0  
Audi Q2             3.0    3.5    0.0    0.0    0.0    0.0  
Audi Q8             5.0    4.0    5.0    5.0    0.0    0.0  

[5 rows x 30 columns]

In [8]:
# mean = np.nanmean(df_cars, axis=1)
# df_normalized = (df_cars.T - mean).T
# df_normalized

In [9]:
from sklearn.metrics.pairwise import pairwise_distances

# Cars Similarity Matrix
car_correlation = 1 - pairwise_distances(df_cars, metric='cosine')
car_correlation[np.isnan(car_correlation)] = 0
print(car_correlation)

[[1.         0.70710678 0.46631498 ... 0.68829738 0.5060454  0.37713396]
 [0.70710678 1.         0.29309732 ... 0.46108397 0.35782813 0.23704354]
 [0.46631498 0.29309732 1.         ... 0.69823613 0.99765642 0.73167783]
 ...
 [0.68829738 0.46108397 0.69823613 ... 1.         0.71495153 0.56470104]
 [0.5060454  0.35782813 0.99765642 ... 0.71495153 1.         0.73157981]
 [0.37713396 0.23704354 0.73167783 ... 0.56470104 0.73157981 1.        ]]


In [10]:
car_correlation[car_correlation < 0] = 0
car_correlation

array([[1.        , 0.70710678, 0.46631498, ..., 0.68829738, 0.5060454 ,
        0.37713396],
       [0.70710678, 1.        , 0.29309732, ..., 0.46108397, 0.35782813,
        0.23704354],
       [0.46631498, 0.29309732, 1.        , ..., 0.69823613, 0.99765642,
        0.73167783],
       ...,
       [0.68829738, 0.46108397, 0.69823613, ..., 1.        , 0.71495153,
        0.56470104],
       [0.5060454 , 0.35782813, 0.99765642, ..., 0.71495153, 1.        ,
        0.73157981],
       [0.37713396, 0.23704354, 0.73167783, ..., 0.56470104, 0.73157981,
        1.        ]])

In [11]:
car_correlation.shape

(125, 125)

In [12]:
df_car_correlation = pd.DataFrame(car_correlation)
df_car_correlation.columns = df_cars.index
df_car_correlation.head()

Cars name  Aston Martin DBX   Audi A4   Audi A8   Audi Q2   Audi Q8  \
0                  1.000000  0.707107  0.466315  0.720750  0.556846   
1                  0.707107  1.000000  0.293097  0.509647  0.393750   
2                  0.466315  0.293097  1.000000  0.765553  0.923256   
3                  0.720750  0.509647  0.765553  1.000000  0.814734   
4                  0.556846  0.393750  0.923256  0.814734  1.000000   

Cars name  Audi RS Q8  BMW 2 Series  BMW 8 Series    BMW M2    BMW X4  ...  \
0            0.707107      0.998618      0.433963  0.816497  0.384015  ...   
1            1.000000      0.668965      0.306858  0.577350  0.257248  ...   
2            0.293097      0.468394      0.843181  0.592269  0.787497  ...   
3            0.509647      0.719754      0.656836  0.882735  0.603086  ...   
4            0.393750      0.556076      0.798655  0.659261  0.731548  ...   

Cars name  Toyota Urban Cruiser  Toyota Vellfire  Toyota Yaris  \
0                      0.277746         0.481683      0.147925   
1                      0.196396         0.340601      0.167358   
2                      0.530061         0.935900      0.465230   
3                      0.449305         0.746422      0.337976   
4                      0.498355         0.885137      0.421742   

Cars name  Volkswagen Polo  Volkswagen T-Roc  Volkswagen Tiguan Allspace  \
0                 0.268269          0.344124                    0.524097   
1                 0.189695          0.216295                    0.324269   
2                 0.511974          0.708247                    0.914782   
3                 0.388857          0.551171                    0.800343   
4                 0.481349          0.661102                    0.986789   

Cars name  Volkswagen Vento  Volvo S60  Volvo XC40  Volvo XC90  
0                  0.236010   0.688297    0.506045    0.377134  
1                  0.187745   0.461084    0.357828    0.237044  
2                  0.468498   0.698236    0.997656    0.731678  
3                  0.393366   0.913851    0.784174    0.619144  
4                  0.446832   0.766551    0.929905    0.665018  

[5 rows x 125 columns]

In [13]:
final_df = df_car_correlation.T
final_df.columns = df_cars.index
final_df.head()

Cars name         Aston Martin DBX   Audi A4   Audi A8   Audi Q2   Audi Q8  \
Cars name                                                                    
Aston Martin DBX          1.000000  0.707107  0.466315  0.720750  0.556846   
Audi A4                   0.707107  1.000000  0.293097  0.509647  0.393750   
Audi A8                   0.466315  0.293097  1.000000  0.765553  0.923256   
Audi Q2                   0.720750  0.509647  0.765553  1.000000  0.814734   
Audi Q8                   0.556846  0.393750  0.923256  0.814734  1.000000   

Cars name         Audi RS Q8  BMW 2 Series  BMW 8 Series    BMW M2    BMW X4  \
Cars name                                                                      
Aston Martin DBX    0.707107      0.998618      0.433963  0.816497  0.384015   
Audi A4             1.000000      0.668965      0.306858  0.577350  0.257248   
Audi A8             0.293097      0.468394      0.843181  0.592269  0.787497   
Audi Q2             0.509647      0.719754      0.656836  0.882735  0.603086   
Audi Q8             0.393750      0.556076      0.798655  0.659261  0.731548   

Cars name         ...  Toyota Urban Cruiser  Toyota Vellfire  Toyota Yaris  \
Cars name         ...                                                        
Aston Martin DBX  ...              0.277746         0.481683      0.147925   
Audi A4           ...              0.196396         0.340601      0.167358   
Audi A8           ...              0.530061         0.935900      0.465230   
Audi Q2           ...              0.449305         0.746422      0.337976   
Audi Q8           ...              0.498355         0.885137      0.421742   

Cars name         Volkswagen Polo  Volkswagen T-Roc  \
Cars name                                             
Aston Martin DBX         0.268269          0.344124   
Audi A4                  0.189695          0.216295   
Audi A8                  0.511974          0.708247   
Audi Q2                  0.388857          0.551171   
Audi Q8                  0.481349          0.661102   

Cars name         Volkswagen Tiguan Allspace  Volkswagen Vento  Volvo S60  \
Cars name                                                                   
Aston Martin DBX                    0.524097          0.236010   0.688297   
Audi A4                             0.324269          0.187745   0.461084   
Audi A8                             0.914782          0.468498   0.698236   
Audi Q2                             0.800343          0.393366   0.913851   
Audi Q8                             0.986789          0.446832   0.766551   

Cars name         Volvo XC40  Volvo XC90  
Cars name                                 
Aston Martin DBX    0.506045    0.377134  
Audi A4             0.357828    0.237044  
Audi A8             0.997656    0.731678  
Audi Q2             0.784174    0.619144  
Audi Q8             0.929905    0.665018  

[5 rows x 125 columns]

In [14]:
final_df.loc['Maruti XL6'].sort_values(ascending=False)[:11]

Cars name
Maruti XL6                       1.000000
Land Rover Range Rover Evoque    0.985355
Mercedes-Benz GLC                0.976590
Mahindra XUV500                  0.974877
Mahindra Scorpio                 0.974023
Mahindra Bolero Pik-Up           0.973779
Mahindra Alturas G4              0.971185
Hyundai Santro                   0.970510
Hyundai Aura                     0.969280
Hyundai Grand i10 Nios           0.968180
Volkswagen Vento                 0.968041
Name: Maruti XL6, dtype: float64

In [15]:
temp = final_df.loc['Maruti XL6'].sort_values(ascending=False)[:11]
list2 = list(temp.index)
print("You may also like : \n", list2[:5])

You may also like : 
 ['Maruti XL6', 'Land Rover Range Rover Evoque', 'Mercedes-Benz GLC', 'Mahindra XUV500', 'Mahindra Scorpio']


# Evaluation

In [16]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df1, test_size=0.30, random_state=31)

In [17]:
print(train.shape)
print(test.shape)

(2625, 3)
(1125, 3)


In [18]:
temp_train = train.copy()
temp_test = test.copy()

In [19]:
temp_train['Ratings'] = temp_train['Ratings'].apply(lambda x: 0 if x >= 0 else 1)
temp_test['Ratings'] = temp_test['Ratings'].apply(lambda x: 1 if x >= 0 else 0)

In [20]:
# Cars not rated by user are marked 1 for later prediction. 
temp_train = temp_train.pivot(
    index = 'Cars name',
    columns = 'Users',
    values = 'Ratings'
).fillna(1)

# Cars not rated by user are marked 0 for later evaluation. 
temp_test = temp_test.pivot(
    index = 'Cars name',
    columns = 'Users',
    values = 'Ratings'
).fillna(0)

In [21]:
temp_train.head()

Users             User1  User10  User11  User12  User13  User14  User15  \
Cars name                                                                 
Aston Martin DBX    0.0     1.0     1.0     1.0     1.0     1.0     1.0   
Audi A4             1.0     1.0     1.0     1.0     1.0     1.0     1.0   
Audi A8             1.0     1.0     1.0     1.0     1.0     1.0     1.0   
Audi Q2             1.0     1.0     1.0     1.0     1.0     1.0     1.0   
Audi Q8             1.0     1.0     1.0     1.0     1.0     1.0     1.0   

Users             User16  User17  User18  ...  User28  User29  User3  User30  \
Cars name                                 ...                                  
Aston Martin DBX     1.0     1.0     1.0  ...     1.0     1.0    1.0     1.0   
Audi A4              1.0     1.0     1.0  ...     1.0     1.0    1.0     1.0   
Audi A8              1.0     1.0     1.0  ...     1.0     1.0    0.0     1.0   
Audi Q2              1.0     1.0     1.0  ...     1.0     1.0    0.0     1.0   
Audi Q8              1.0     1.0     1.0  ...     1.0     1.0    0.0     1.0   

Users             User4  User5  User6  User7  User8  User9  
Cars name                                                   
Aston Martin DBX    1.0    1.0    1.0    1.0    1.0    1.0  
Audi A4             1.0    1.0    1.0    1.0    1.0    1.0  
Audi A8             0.0    0.0    0.0    0.0    1.0    1.0  
Audi Q2             0.0    0.0    1.0    1.0    1.0    1.0  
Audi Q8             0.0    1.0    1.0    1.0    1.0    1.0  

[5 rows x 30 columns]

In [22]:
temp_test.head()

Users             User1  User10  User11  User12  User13  User14  User15  \
Cars name                                                                 
Aston Martin DBX    0.0     0.0     0.0     0.0     0.0     0.0     0.0   
Audi A4             1.0     0.0     0.0     0.0     0.0     0.0     0.0   
Audi A8             1.0     0.0     0.0     0.0     0.0     0.0     0.0   
Audi Q2             1.0     0.0     0.0     0.0     0.0     0.0     0.0   
Audi Q8             1.0     0.0     0.0     0.0     0.0     0.0     0.0   

Users             User16  User17  User18  ...  User28  User29  User3  User30  \
Cars name                                 ...                                  
Aston Martin DBX     0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi A4              0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi A8              0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi Q2              0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi Q8              0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   

Users             User4  User5  User6  User7  User8  User9  
Cars name                                                   
Aston Martin DBX    0.0    0.0    0.0    0.0    0.0    0.0  
Audi A4             0.0    0.0    0.0    0.0    0.0    0.0  
Audi A8             0.0    0.0    0.0    0.0    1.0    0.0  
Audi Q2             0.0    0.0    0.0    0.0    0.0    0.0  
Audi Q8             0.0    1.0    1.0    1.0    0.0    0.0  

[5 rows x 30 columns]

## Prediction

In [23]:
cars_predicted_ratings = np.dot(car_correlation, df_cars.fillna(0))
cars_predicted_ratings

array([[259.4172773 ,  94.52874093,  84.40022968, ..., 121.33284393,
        102.83481743,  93.98001446],
       [219.09470998,  68.13935039,  61.15346001, ...,  87.31790904,
         73.86071323,  67.55865267],
       [324.79308998, 188.2031363 , 168.21317108, ..., 239.17720084,
        205.07420551, 187.14881713],
       ...,
       [292.99501249, 134.01928189, 119.485157  , ..., 171.88675751,
        145.10352623, 132.63035679],
       [332.89880267, 188.69081199, 168.66704853, ..., 239.84872416,
        205.57791311, 187.61952078],
       [336.93483709, 227.19539198, 208.80960992, ..., 267.04486365,
        237.19288875, 222.48173133]])

In [24]:
train_rating = np.multiply(cars_predicted_ratings, temp_train)
train_rating.head()

Users                  User1      User10      User11      User12      User13  \
Cars name                                                                      
Aston Martin DBX    0.000000   94.528741   84.400230   81.129006   80.330010   
Audi A4           219.094710   68.139350   61.153460   59.111471   58.328412   
Audi A8           324.793090  188.203136  168.213171  161.411351  159.894123   
Audi Q2           315.064544  147.898086  131.716427  127.052609  125.572561   
Audi Q8           328.403447  177.212859  158.092849  152.283219  150.560283   

Users                 User14      User15      User16      User17      User18  \
Cars name                                                                      
Aston Martin DBX   80.003817   63.726052   73.729614   71.895163   73.090268   
Audi A4            58.005935   46.579556   53.533021   53.263628   53.032906   
Audi A8           158.708143  126.855228  146.403476  143.468360  145.374746   
Audi Q2           124.541215   99.532015  114.712313  112.586465  113.869511   
Audi Q8           149.230222  119.395419  137.699119  135.202178  137.152439   

Users             ...      User28      User29       User3     User30  \
Cars name         ...                                                  
Aston Martin DBX  ...   54.995050   53.711807  173.111990  46.366570   
Audi A4           ...   40.380048   39.385691  122.007054  34.579093   
Audi A8           ...  108.222709  105.256145    0.000000  91.667403   
Audi Q2           ...   85.905280   83.842075    0.000000  72.629642   
Audi Q8           ...  102.314398   99.586641    0.000000  86.771170   

Users                  User4       User5       User6       User7       User8  \
Cars name                                                                      
Aston Martin DBX  148.843250  133.612210  124.943817  121.332844  102.834817   
Audi A4           104.934434   94.803041   89.268760   87.317909   73.860713   
Audi A8             0.000000    0.000000    0.000000    0.000000  205.074206   
Audi Q2             0.000000    0.000000  193.914943  188.928158  159.814295   
Audi Q8             0.000000  246.747261  233.687773  228.647275  191.781278   

Users                  User9  
Cars name                     
Aston Martin DBX   93.980014  
Audi A4            67.558653  
Audi A8           187.148817  
Audi Q2           146.252505  
Audi Q8           176.477096  

[5 rows x 30 columns]

In [25]:
from sklearn.preprocessing import MinMaxScaler
X = train_rating.copy() 
X = X[X > 0]

scaler = MinMaxScaler(feature_range = (1, 5))
scaler.fit(X)
y = (scaler.transform(X))
y = pd.DataFrame(y)
y.tail()

0         1         2         3         4         5         6   \
120       NaN  2.961774  2.813256  2.729276  2.705674  2.724652  2.590219   
121  4.687434       NaN       NaN  4.959570  4.958010       NaN       NaN   
122       NaN  2.223245  2.127229  2.076479  2.062738  2.073712  1.987950   
123  3.886397  3.238374  3.077642  2.971196  2.949373  2.975767  2.820138   
124       NaN       NaN       NaN       NaN       NaN  3.776430  3.550615   

           7         8         9   ...        20        21        22  \
120  2.610675  2.593281  2.610490  ...  2.474341  2.480102       NaN   
121       NaN       NaN  4.963910  ...  5.000000       NaN       NaN   
122  2.001766  1.983396  1.995628  ...  1.926434  1.937733       NaN   
123  2.843315  2.823244  2.833816  ...  2.677355  2.682133       NaN   
124  3.579351  3.562275  3.562568  ...  3.339704  3.346593  4.256733   

           23  24        25        26        27        28        29  
120  2.477446 NaN       NaN       NaN       NaN  3.127590  3.009176  
121       NaN NaN  4.853397       NaN       NaN       NaN       NaN  
122  1.921323 NaN  2.585780  2.532924  2.477162  2.325679  2.237201  
123  2.680220 NaN       NaN  3.718590       NaN  3.450980  3.282704  
124  3.341695 NaN       NaN  4.102739       NaN  4.039268       NaN  

[5 rows x 30 columns]

Bu using this matrix we can find the rating for the car that could be given by EXISTING USER

In [26]:
# FOR CONFIRMATION
traint = train.pivot(
    index = 'Cars name',
    columns = 'Users',
    values = 'Ratings'
)
traint.tail()

Users                       User1  User10  User11  User12  User13  User14  \
Cars name                                                                   
Volkswagen Tiguan Allspace    3.5     NaN     NaN     NaN     NaN     NaN   
Volkswagen Vento              NaN     4.5     4.5     NaN     NaN     4.5   
Volvo S60                     4.5     NaN     NaN     NaN     NaN     NaN   
Volvo XC40                    NaN     NaN     NaN     NaN     NaN     NaN   
Volvo XC90                    4.0     5.0     5.0     4.5     5.0     NaN   

Users                       User15  User16  User17  User18  ...  User28  \
Cars name                                                   ...           
Volkswagen Tiguan Allspace     NaN     NaN     NaN     NaN  ...     NaN   
Volkswagen Vento               5.0     4.5     4.5     NaN  ...     NaN   
Volvo S60                      NaN     NaN     NaN     NaN  ...     NaN   
Volvo XC40                     NaN     NaN     NaN     NaN  ...     NaN   
Volvo XC90                     NaN     NaN     NaN     NaN  ...     NaN   

Users                       User29  User3  User30  User4  User5  User6  User7  \
Cars name                                                                       
Volkswagen Tiguan Allspace     NaN    4.5     NaN    4.5    2.5    5.0    3.5   
Volkswagen Vento               5.0    5.0     4.5    4.5    NaN    2.5    4.5   
Volvo S60                      NaN    5.0     NaN    5.0    NaN    NaN    NaN   
Volvo XC40                     NaN    5.0     NaN    5.0    5.0    NaN    4.5   
Volvo XC90                     NaN    NaN     NaN    5.0    5.0    NaN    5.0   

Users                       User8  User9  
Cars name                                 
Volkswagen Tiguan Allspace    NaN    NaN  
Volkswagen Vento              3.5    4.5  
Volvo S60                     NaN    NaN  
Volvo XC40                    NaN    NaN  
Volvo XC90                    NaN    1.5  

[5 rows x 30 columns]

In [27]:
y.iloc[1]

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    1.0
26    1.0
27    1.0
28    1.0
29    1.0
Name: 1, dtype: float64

### Prediction for the cars rated by the user

In [28]:
test_DF = test.pivot(
    index = 'Cars name',
    columns = 'Users',
    values = 'Ratings'
)

In [29]:
test_car_correlation = 1 - pairwise_distances(test_DF.fillna(0), metric = 'cosine')
# test_car_correlation[np.isnan(test_car_correlation)] = 0
test_car_correlation[test_car_correlation < 0] = 0

In [30]:
test_car_predicted_ratings = np.dot(test_car_correlation, test_DF.fillna(0))
test_car_predicted_ratings = np.multiply(test_car_predicted_ratings, temp_test)
test_car_predicted_ratings.head()

Users                 User1  User10  User11  User12  User13  User14  User15  \
Cars name                                                                     
Aston Martin DBX   0.000000     0.0     0.0     0.0     0.0     0.0     0.0   
Audi A4           95.612571     0.0     0.0     0.0     0.0     0.0     0.0   
Audi A8           62.286083     0.0     0.0     0.0     0.0     0.0     0.0   
Audi Q2           95.612571     0.0     0.0     0.0     0.0     0.0     0.0   
Audi Q8           64.424517     0.0     0.0     0.0     0.0     0.0     0.0   

Users             User16  User17  User18  ...  User28  User29  User3  User30  \
Cars name                                 ...                                  
Aston Martin DBX     0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi A4              0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi A8              0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi Q2              0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi Q8              0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   

Users             User4      User5      User6     User7      User8  User9  
Cars name                                                                  
Aston Martin DBX    0.0   0.000000   0.000000   0.00000   0.000000    0.0  
Audi A4             0.0   0.000000   0.000000   0.00000   0.000000    0.0  
Audi A8             0.0   0.000000   0.000000   0.00000  46.404648    0.0  
Audi Q2             0.0   0.000000   0.000000   0.00000   0.000000    0.0  
Audi Q8             0.0  37.393103  47.240593  38.03653   0.000000    0.0  

[5 rows x 30 columns]

In [31]:
X2 = test_car_predicted_ratings.copy() 
X2 = X2[X2 > 0]

scaler = MinMaxScaler(feature_range = (1, 5))
scaler.fit(X2)
y2 = (scaler.transform(X2))
y2 = pd.DataFrame(y2)
y2.head()

0   1   2   3   4   5   6   7   8   9   ...  20  21  22  23  24  \
0       NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN   
1  5.000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN   
2  2.862901 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN   
3  5.000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN   
4  3.000031 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN   

         25        26   27        28  29  
0       NaN       NaN  NaN       NaN NaN  
1       NaN       NaN  NaN       NaN NaN  
2       NaN       NaN  NaN  4.827056 NaN  
3       NaN       NaN  NaN       NaN NaN  
4  2.942693  4.189478  5.0       NaN NaN  

[5 rows x 30 columns]

In [32]:
#to confirm
temp_test.head()

Users             User1  User10  User11  User12  User13  User14  User15  \
Cars name                                                                 
Aston Martin DBX    0.0     0.0     0.0     0.0     0.0     0.0     0.0   
Audi A4             1.0     0.0     0.0     0.0     0.0     0.0     0.0   
Audi A8             1.0     0.0     0.0     0.0     0.0     0.0     0.0   
Audi Q2             1.0     0.0     0.0     0.0     0.0     0.0     0.0   
Audi Q8             1.0     0.0     0.0     0.0     0.0     0.0     0.0   

Users             User16  User17  User18  ...  User28  User29  User3  User30  \
Cars name                                 ...                                  
Aston Martin DBX     0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi A4              0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi A8              0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi Q2              0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   
Audi Q8              0.0     0.0     0.0  ...     0.0     0.0    0.0     0.0   

Users             User4  User5  User6  User7  User8  User9  
Cars name                                                   
Aston Martin DBX    0.0    0.0    0.0    0.0    0.0    0.0  
Audi A4             0.0    0.0    0.0    0.0    0.0    0.0  
Audi A8             0.0    0.0    0.0    0.0    1.0    0.0  
Audi Q2             0.0    0.0    0.0    0.0    0.0    0.0  
Audi Q8             0.0    1.0    1.0    1.0    0.0    0.0  

[5 rows x 30 columns]

In [33]:
test_original = test.pivot(
    index = 'Cars name',
    columns = 'Users',
    values = 'Ratings'
)

In [34]:
from numpy import *
total_non_nan = np.count_nonzero(~np.isnan(y2))

# rmse = (sum(sum((test_original - y2)**2))/total_non_nan)**0.5
# print(rmse)

In [35]:
import math

lista = []
for i in range(0,125):
    templist = [b / m for b,m in zip(list(y2.iloc[i].values),list(test_original.iloc[i].values))]
    cleanedList = [x for x in templist if (math.isnan(x) == False)]
    lista.append(sum(cleanedList))
#   len(lista)

In [36]:
accuracy = (sum(lista)/total_non_nan)*100
print("Accuracy of this model is : {} %".format(np.round(accuracy, 2)))

Accuracy of this model is : 83.3 %


# =============================================================

In [37]:
# test_DF = df1.pivot(
#     index = 'Cars name',
#     columns = 'Users',
#     values = 'Ratings'
# )

# temp_test2 = test_DF.copy()
# temp_test2['Ratings'] = df1['Ratings'].apply(lambda x: 1 if x >= 0 else 0)

# temp_test2 = df1.pivot(
#     index = 'Cars name',
#     columns = 'Users',
#     values = 'Ratings'
# )

# mean = np.nanmean(test_DF, axis = 1)
# test_df_normalized = (test_DF.T - mean).T

# test_car_correlation = 1 - pairwise_distances(test_df_normalized.fillna(0), metric = 'cosine')
# # test_car_correlation[np.isnan(test_car_correlation)] = 0
# test_car_correlation[test_car_correlation < 0] = 0

# test_car_predicted_ratings = np.dot(test_car_correlation, test_DF.fillna(0))
# test_car_predicted_ratings = np.multiply(test_car_predicted_ratings, temp_test2)
# test_car_predicted_ratings.head()

In [38]:
# X3 = test_car_predicted_ratings.copy() 
# X3 = X3[X3 > 0]

# scaler = MinMaxScaler(feature_range = (1, 5))
# scaler.fit(X3)
# y3 = (scaler.transform(X3))
# y3 = pd.DataFrame(y3)
# y3.head()

In [39]:
# from numpy import *
# total_non_nan = np.count_nonzero(~np.isnan(y3))

# import math

# lista = []
# for i in range(0,125):
#     templist = [b / m for b,m in zip(list(y3.iloc[i].values),list(test_DF.iloc[i].values))]
#     cleanedList = [x for x in templist if (math.isnan(x) == False)]
#     lista.append(sum(cleanedList))
    
# accuracy = (sum(lista)/total_non_nan)*100
# print("Accuracy of this model is : {} %".format(np.round(accuracy, 2)))